language: objective-c
osx_image: xcode8.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=FireMock.xcodeproj
  - IOS_FRAMEWORK_SCHEME="FireMock"
  - IOS_SDK=iphonesimulator10.2
matrix:
  - DESTINATION="OS=10.2,name=iPhone 7 Plus"
  - SDK="$IOS_SDK"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO build | xcpretty;
